### ISSUE TITLE
如何实现“再次确认密码”equal？

### ISSUE THREAD

**Issue by SunsetWan** [WLDragon/SMValidator#10]
作者，您好！

![screen shot 2017-07-24 at 11 03 59 pm](https://user-images.githubusercontent.com/16316111/28530297-f4247f3e-70c5-11e7-83a0-cb0a4f66e8ba.png)
ng…]()
以上script内代码，是本人参照您的Demo写出来的。运行时，始终无法实现“确认两次输入密码是否一致”的功能。
Chrome调试报错如下:
<img width="441" alt="screen shot 2017-07-24 at 11 03 45 pm" src="https://user-images.githubusercontent.com/16316111/28530067-19fb301e-70c5-11e7-85a4-6ac36a9451ec.png">
我还是没想通哪里不对。
我刚接触js不足俩礼拜，望您能不吝赐教，谢谢！

**Comment by WLDragon** [comment]
@SunsetWan 额，你没定义id，用equal(input[name="rpasswd"])，js才学了不足俩礼拜没关系，你是没学css选择器吧

**Comment by SunsetWan** [comment]
谢谢您的批评！
请问是定义“再次输入一次密码”这个input的id吗？ 我想请求您说详细一点
我把script中fields{}中rpasswd后的‘equal(#password)’改成‘equal(input[name="rpasswd"])’，运行了一遍还是没能成功，有点苦恼..

**Comment by WLDragon** [comment]
@SunsetWan 是我写错了，equal里填的是目标input的选择器，应该改为`equal(input[name="passwd"])`，不是rpasswd，其实我不是做web前端的，我就心血来潮写了这个工具而已

**Comment by SunsetWan** [comment]
@WLDragon 好的，再次感谢您！
