### ISSUE TITLE
How to check password and repeat-password matching each other

### ISSUE THREAD

**Issue by ephraimguo** [WLDragon/SMValidator#12]
I am a beginner of the web technology and I would like to know about how to verify if the password and repeat password from two individual input text box.

```
<label>Password</label>
<input type="password" name="password" class="form-control" >
<br>
<label>Repeat Password</label>
 <input type="password" name="repeatpassword" class="form-control" >
```
so for this 2 input, how can I verifiy the input values from both inputs and return true once they are having the same values.

Thanks so much!

**Comment by WLDragon** [comment]
You can use the keyword "equal" in repeat password input.
```
<input type="password" name="repeatpassword" data-rule="equal([name='password'])">
```
You can get more details in the demo of source code

**Comment by ephraimguo** [comment]
That's cool, thanks !
