### ISSUE TITLE
怎么判断验证是否成功,就是我提交表单不用submit，我用其他按钮怎么判断验证是否成功

### ISSUE THREAD

**Issue by ErnestWangZuNian** [WLDragon/SMValidator#4]
怎么判断验证是否成功,就是我提交表单不用submit，我用其他按钮怎么判断验证是否成功

**Comment by WLDragon** [comment]
点击按钮时使用SMValidator.validate(inputs)方法，全部inputs验证通过才返回true。inputs可以是css选择器，也可以是包含input对象的数组。
