### ISSUE TITLE
同一个页面，同一个input框不会多吃进行async的方法

### ISSUE THREAD

**Issue by paulfrom** [WLDragon/SMValidator#7]
`function modal_sub(){
    asyncAccountName();
    if(SMValidator.validate('#addFrom')){
....
}
}`
一旦当asyncAccountName()通过一次，再次提交就不会验证了

**Comment by WLDragon** [comment]
不明白你的意思，能说详细点吗？/冷汗

**Comment by paulfrom** [comment]
不好意思，我刚刚看错了，应该是缓存问题。。。。。没想到回复这么快。
想请教一下做服务器端的验证是必须先调用一下同步的方法然后再SMValidator.validate('#addFrom')才能生效吗？

**Comment by WLDragon** [comment]
看教程3第2点要先设置async才能用服务器验证的
