### ISSUE TITLE
如何不用表单submit属性，手动验证呢？

### ISSUE THREAD

**Issue by wzc0x0** [WLDragon/SMValidator#9]
看了你的插件很好用，但是有一点，如何在不采用表单submit属性验证提交表单，而是手动验证的方式，我这边采用SMValidator.validate()的方式，发现每次都是true，应该怎么配置？谢谢作者解答

**Comment by WLDragon** [comment]
我知道你的问题了，你应该是使用了&分割符，然后最后一条规则确实是验证通过了。SMValidator.validate()返回的结果是通过最后一个结果来判断的，现在已经修复，更新到1.2.7版本即可
